### ISSUE TITLE
Order Process

### ISSUE THREAD

**Issue by AthulKrishna14310** [saneenKP/food-app#1]
**UI**
![20210421_193130](https://user-images.githubusercontent.com/37478917/115576661-5a39a280-a2e1-11eb-806b-855b20feea69.jpg)

**Order Database**

![20210421_202623](https://user-images.githubusercontent.com/37478917/115576888-8e14c800-a2e1-11eb-9d89-aa34ccf74dfa.jpg)

**Tasks**

- [x] **Screen X** Item list items  should have an attribute of food price (This screen is the same UI as done till now)
- [x] **Screen X** Place order button should be updated on selection on-increment / decrement buttons by showing total cost on the Place Order Button. When Place order Button is tapped load Screen Y
- [x] **Screen Y** Create Screen Y with provided UI
- [x] **Screen Y** Location X Y coordinates should be loaded but they should not be displayed in UI
        -[ ] Location Permission should be handled accordingly
- [ ]**Screen Y**  Location Details should be loaded and Displayed in UI
- [x] **Screen Y** Address title should have 4 text fields ( As mentioned in UI ) and this should be loaded from shared preference if exists, else this data should be typed manually. When a user forwards for payment these text fields data should be saved in the shared preference.
- [x] **Screen Y** If the Pay and Place order button is clicked it should be directed to the payment gateway of razor pay
- [x] **Screen Z** Create Screen Z with provided UI using text views and image button to show order status
- [x] **Screen Y** If Place order by COD is clicked, the user should have an alert dialogue to confirm the order if accepted direct user to Screen Z
- [x] **Screen Z** On the onStart of Screen Z update the database as _Order Database_ 

**Tutorial**
  
 Payment Gateway
- https://www.youtube.com/watch?v=gCwcP63sYxI
- https://www.youtube.com/watch?v=IQkwzdO-jhY
- https://razorpay.com/docs/payment-gateway/android-integration/standard/

Implement Location
- https://www.youtube.com/watch?v=UKUb7C3b0us

**Comment by AthulKrishna14310** [comment]
- [ ] Progessbar while loading location
- [ ] No Default address for new user ( Now its loading the data of Saneen)
- [ ] When dishes activity is opened the button at bottom should not be visible.
- [ ] Ongoing order should be kept as a badge on each activity top.
- [ ] Cannot proceed to Order without typing all address fields
- [ ] After address details , there should be a Title called Food Details to show the selected food and quantity
- [ ] There should be button on dishes activity to clear selected dishes
- [ ] When the user goes back from place order activity to back selected item should be updated within items
