### ISSUE TITLE
Content Admin App

### ISSUE THREAD

**Issue by AthulKrishna14310** [saneenKP/food-app#3]
The client's app has 2 app builds, one for the general public and one for content admins. The content admin's app  has just few actions with the existing general public client app

- _Please create a new branch before proceeding to do this task in the same repository. Branch name " foodapp-content-admin"_
- _After doing this task on commit and push to " foodapp-content-admin"_ 

**Task 1 - Hotel Actions**
<img src ="https://user-images.githubusercontent.com/37478917/120061224-d4480e80-c079-11eb-9720-e5a807d02940.jpeg" width=240>
- [x] Set a floating action button in this activity
- [x] if the floating action button clicked, a dialog interface should be shown with text fields for adding a new hotel.
- [x] if long-press on an item, the same dialog interface should be shown by loading initial data in the provided text fields, User 
      can edit text fields to edit the hotel data accordingly.
- [x] The same dialog should have a delete button to delete the selected hotel.
- [x] The same dialog should also contain a button to upload and add a cover photo of the hotel

**Task 2 - Food Actions**
<img src ="https://user-images.githubusercontent.com/37478917/120061857-c5169000-c07c-11eb-84d7-910db0b1bafd.jpeg" width = 240 >
- [x] Set a floating action button in this activity
- [x] if the floating action button clicked, a dialog interface should be shown with text fields for adding new food.
- [x] if long-press on an item, the same dialog interface should be shown by loading initial data in the provided text fields, User 
      can edit text fields to edit the food data accordingly.
- [x] The same dialog should have a delete button to delete the selected food.
- [x] The same dialog should also contain a button to upload and add a cover photo of the food

**Task 3 - Service Category  Actions**
<img src  ="https://user-images.githubusercontent.com/37478917/120062221-a1ece000-c07e-11eb-9020-8dbdac339b52.jpeg" width=240>

- [x] Set a floating action button in this activity
- [x] if the floating action button clicked, a dialog interface should be shown with text fields for adding a new service category.
- [x] if long-press on an item, the same dialog interface should be shown by loading initial data in the provided text fields, User 
      can edit text fields to edit the service category data accordingly.
- [x] The same dialog should have a delete button to delete the selected service category.
- [x] The same dialog should also contain a button to upload and add a cover photo of the service category

**Task 4 - Vendor  Actions**
<image src = "https://user-images.githubusercontent.com/37478917/120062529-53404580-c080-11eb-83d5-078c24d09cee.jpeg"
width= 240>

- [x] Set a floating action button in this activity
- [x] if the floating action button clicked, a dialog interface should be shown with text fields for adding a new vendor.
- [x] if long-press on an item, the same dialog interface should be shown by loading initial data in the provided text fields, User 
      can edit text fields to edit the vendor data accordingly.
- [x] The same dialog should have a delete button to delete the selected vendor.
- [x] The same dialog should also contain a button to upload and add a cover photo of the vendor

**Constraints**

1. No need to load, cover image on the dialog, only add a button to select the cover image
2. Please create a new branch before proceeding to do this task in the same repository for this purpose. Branch name 
" foodapp- content-admin"

**Tutorial (Cut and paste codes)**

- Upload cover-photo

          ```
          mButton.setOnClickListener(view -> CropImage.activity()
                          .setGuidelines(CropImageView.Guidelines.ON)
                          .setAspectRatio(1, 1)
                          .start(Activity.this));
          ```
 ```
          @Override
              protected void onActivityResult(int requestCode, int resultCode, @Nullable Intent data) {
                  super.onActivityResult(requestCode, resultCode, data);
                                 CropImage.ActivityResult result = CropImage.getActivityResult(data);
                         if (resultCode == RESULT_OK) {
                             
                            mButton.setVisiblity(INVISIBLE);
                             Uri resultUri = Objects.requireNonNull(result).getUri();
                             File temp=new File(resultUri.getPath());
                             final String current_u_i_d = Objects.requireNonNull(FirebaseAuth.getInstance().getCurrentUser()).getUid();
                           
                                     //set your storage reference
                                      final StorageReference filepath = FirebaseStorage.getInstance()
                                     .getReference().child("cover_photo")
                                     .child(Objects.requireNonNull(resultUri.getLastPathSegment()));
                             
                                    filepath.putFile(resultUri)
                                     .addOnCompleteListener(
                                     task -> {
                                         if(task.isSuccessful()){
                                             filepath.getDownloadUrl().addOnCompleteListener(task1 -> {
                                                 if(task.isSuccessful()){
                                                    
                                                    databaseReference.child("your_cover_node")
                                                    .setValue(task1.getResult().toString()).addOnCompleteListener(new 
                                                      OnCompleteListener<Void>() {
                                                        @Override
                                                        public void onComplete(@NonNull Task<Void> task) {
                                                            if(task.isSuccessful()){
                                                                circularProgressIndicator.setProgress(0);
                                                                circularProgressIndicator.setVisibility(View.INVISIBLE);
                                                                mButton.setVisibility(View.VISIBLE);
                                                            }else {
                                                                showDialogMessageError("Network Error"+
                                                                        Objects.requireNonNull(task.getException()).getMessage());
                                                                circularProgressIndicator.setVisibility(View.INVISIBLE);
                                                                mButton.setVisibility(View.VISIBLE);
                                                            }
                                                        }
                                                    });
                                                 }else{
                                                     showDialogMessageError("Network Error"+
                                                             Objects.requireNonNull(task.getException()).getMessage());
                                                     circularProgressIndicator.setProgress(0);
                                                     circularProgressIndicator.setVisibility(View.INVISIBLE);
                                                     mButton.setVisibility(View.VISIBLE);
                                                 }
                                             });
                                         }else{
                                             showDialogMessageError("Network Error"+
                                                     Objects.requireNonNull(task.getException()).getMessage());
                                             circularProgressIndicator.setProgress(0);
                                             circularProgressIndicator.setVisibility(View.INVISIBLE);
                                             mButton.setVisibility(View.VISIBLE);
                                         }
                                     }).addOnProgressListener(taskSnapshot -> {
                                          circularProgressIndicator.setVisibility(View.VISIBLE);
                                          double progress = (100*taskSnapshot.getBytesTransferred())/taskSnapshot.getTotalByteCount();
                                          circularProgressIndicator.setProgressCompat((int)progress,true);
                                         
                                     }).addOnFailureListener(e -> {
                                          showDialogMessageError(""+e.getMessage());
                                          circularProgressIndicator.setVisibility(View.INVISIBLE);
                                          mButton.setVisibility(View.VISIBLE);
                                     });
          
                         }
          
              }
```

-  [Alert Dialog with EditText](https://www.youtube.com/watch?v=xaxG54VulKk)
  

- [Git Branching ](https://www.youtube.com/watch?v=b6GMwT35I38) 
  after committing to the branch push to it using
  `git push origin "foodapp-content-admin"`

  overall way of branching github 

```
  git branch "foodapp-content-admin"
  git checkout "foodapp-content-admin"
  git add .
  git commit -m "update"
  git push origin "foodapp-content-admin"
```
